### ISSUE TITLE
CalEvent.parse does not parse zone offsets

### ISSUE THREAD

**Issue by pawelkaczor** [eikek/calev#360]
val cal  = CalEvent.unsafe("Mon *-*-* 15:00:00")
val calWithZone = cal.copy(zone = Some(ZoneOffset.UTC))

calWithZone.asString produces: Mon *-*-* 15:00:00 Z

It should produce: Mon *-*-* 15:00:00 UTC

**Comment by eikek** [comment]
Why do you think this is wrong? It follows the iso8601 standard, where `Z` is used to mean no offset from UTC.

**Comment by pawelkaczor** [comment]
Ok, you are right. The problem is that CalEvent.unsafe throws exception when parsing "Mon --* 15:00:00 Z"

Can we fix it?

**Comment by eikek** [comment]
Yes true! either don't render or be able to parse it :)

If you give it a zone instead of an offset it renders UTC
```
@ CalEvent.unsafe("Mon *-*-* 15:00:00").copy(zone = Some(ZoneId.of("UTC"))).asString
res14: String = "Mon *-*-* 15:00:00 UTC"
```
I think it's both ok. Maybe just parsing it as no offset is fine.

**Comment by pawelkaczor** [comment]
I would expect Calev.asString and Calev.unsafe to be compatible. They are not.

**Comment by eikek** [comment]
Right, there are two ways now: either don't render `Z` or allow to parse it. So I wrote that maybe allowing to parse it is good.

**Comment by pawelkaczor** [comment]
Yes, I think parsing Z should work.
