### ISSUE TITLE
Inconsistent output dates between calev-core and systemd cli

### ISSUE THREAD

**Issue by Sheryv** [eikek/calev#553]
Value of next elapse calculated by this library is different from the output of `systemd-analyze calendar` command for the same input values. Example:
- systemd
```bash
$ systemd-analyze calendar --iterations=1 "*-2-* 10:00:00"
  Original form: *-2-* 10:00:00
Normalized form: *-02-* 10:00:00
    Next elapse: Sat 2025-02-01 10:00:00 CET
       (in UTC): Sat 2025-02-01 09:00:00 UTC
       From now: 10 months 13 days left

$ date
Wed 20 Mar 2024 10:01:36 AM CET
```
- main method from calev-core
```
$ sbt core/run --ref "2024-03-20T10:01:00" "*-2-* 10:00:00"
Normalized:  *-02-* 10:00:00
Reference:   2024-03-20T10:01
Next Elapses:
- 2025-02-21T10:00
```
systemd returns `2025-02-01` and calev: `2025-02-21`. Is this difference intentional or is it a bug?

**Comment by eikek** [comment]
This is a bug, 2025-02-21 doesn't make sense I believe. There are some tests defined in [this file](https://github.com/eikek/calev/blob/master/modules/core/.jvm/src/test/resources/com/github/eikek/calev/trigger-data.txt) - if possible, would you mind adding a failing one? Of course, should you have time and energy to fix it, even better 😏

**Comment by Sheryv** [comment]
I took a quick look at the parser and I have no idea how to fix it
